// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzjkryznjfzdgbutgphi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6amtyeXpuamZ6ZGdidXRncGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjE5MTQsImV4cCI6MjA2OTQ5NzkxNH0.OgTeD-J1F2VvLSF6j_z5La97AH1mFu60Krm1F8pnwJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});